title: Akbarul's Profile
page-top-title: Official Site.
top-section-bg-text: Senior Software & AI Engineer
top-section-bg-text-sub: Driving digital automation with advanced AI solutions.
home-subtitle: Arif Akbarul Huda
copyright-text: '&copy; Akbarul 2025. All Rights Reserved.'
