title: Akbarul's Profile
page-top-title: Official Site.
top-section-bg-text: Software & AI Engineer
top-section-bg-text-sub: Optimizing human productivity through Multi-Model Agentic AI workflows.
home-subtitle: Arif Akbarul Huda
copyright-text: '&copy; Akbarul 2026. All Rights Reserved.'
