title: Akbarul's Homepage
page-top-title: Akbarul
top-section-bg-text: AI Engineer & Consultant
top-section-bg-text-sub: Driving digital transformation with advanced AI solutions and innovative consulting services.
home-subtitle: Arif Akbarul Huda
copyright-text: '&copy; Akbarul 2025. All Rights Reserved.'
